"""add_email_account_and_import_log

Revision ID: 7fdff7a46e18
Revises: df01613ac9d6
Create Date: 2026-04-23 18:31:28.028583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fdff7a46e18'
down_revision: Union[str, Sequence[str], None] = 'df01613ac9d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('imap_host', sa.String(length=255), nullable=False),
    sa.Column('imap_port', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('folder', sa.String(length=120), nullable=False),
    sa.Column('use_ssl', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_import_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('email_import_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email_account_id', sa.Integer(), nullable=False),
    sa.Column('email_uid', sa.String(length=120), nullable=False),
    sa.Column('email_subject', sa.String(length=500), nullable=False),
    sa.Column('email_from', sa.String(length=255), nullable=False),
    sa.Column('parser_used', sa.String(length=120), nullable=False),
    sa.Column('transaction_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('imported_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['email_account_id'], ['email_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('email_import_logs')
    op.drop_table('email_accounts')
    # ### end Alembic commands ###
