"""initial

Revision ID: df01613ac9d6
Revises: 
Create Date: 2026-04-23 10:32:45.576881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'df01613ac9d6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('entity_type', sa.String(length=80), nullable=False),
    sa.Column('entity_id', sa.String(length=80), nullable=False),
    sa.Column('details', sqlite.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bill_import_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_name', sa.String(length=120), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'FAILED', name='importjobstatus'), nullable=False),
    sa.Column('raw_count', sa.Integer(), nullable=False),
    sa.Column('normalized_count', sa.Integer(), nullable=False),
    sa.Column('merged_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('logs', sqlite.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('merged_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('occurred_on', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('direction', sa.Enum('INCOME', 'EXPENSE', name='billdirection'), nullable=False),
    sa.Column('merchant_name', sa.String(length=200), nullable=False),
    sa.Column('normalized_merchant', sa.String(length=200), nullable=False),
    sa.Column('source_name', sa.String(length=120), nullable=False),
    sa.Column('category', sa.String(length=120), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('duplicate_count', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_call_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('classifier_name', sa.String(length=80), nullable=False),
    sa.Column('request_payload', sqlite.JSON(), nullable=False),
    sa.Column('response_payload', sqlite.JSON(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('task_date', sa.Date(), nullable=True),
    sa.Column('start_at', sa.DateTime(), nullable=True),
    sa.Column('due_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('SCHEDULED', 'IN_PROGRESS', 'ON_HOLD', 'COMPLETED', 'CANCELLED', name='taskstatus'), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('tags', sqlite.JSON(), nullable=False),
    sa.Column('is_pinned', sa.Boolean(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('value', sqlite.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('raw_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('import_job_id', sa.Integer(), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('source_name', sa.String(length=120), nullable=False),
    sa.Column('raw_data', sqlite.JSON(), nullable=False),
    sa.Column('original_reference', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['import_job_id'], ['bill_import_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_status_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('old_status', sa.Enum('SCHEDULED', 'IN_PROGRESS', 'ON_HOLD', 'COMPLETED', 'CANCELLED', name='taskstatus'), nullable=True),
    sa.Column('new_status', sa.Enum('SCHEDULED', 'IN_PROGRESS', 'ON_HOLD', 'COMPLETED', 'CANCELLED', name='taskstatus'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_subitems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='subitemstatus'), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('normalized_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('import_job_id', sa.Integer(), nullable=False),
    sa.Column('raw_transaction_id', sa.Integer(), nullable=True),
    sa.Column('occurred_on', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('direction', sa.Enum('INCOME', 'EXPENSE', name='billdirection'), nullable=False),
    sa.Column('merchant_name', sa.String(length=200), nullable=False),
    sa.Column('normalized_merchant', sa.String(length=200), nullable=False),
    sa.Column('source_name', sa.String(length=120), nullable=False),
    sa.Column('channel', sa.String(length=120), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('card_last4', sa.String(length=8), nullable=False),
    sa.Column('dedupe_key', sa.String(length=255), nullable=False),
    sa.Column('merge_status', sa.Enum('UNMERGED', 'MERGED', 'UNDONE', name='mergestatus'), nullable=False),
    sa.Column('category_suggested', sa.String(length=120), nullable=False),
    sa.Column('category_final', sa.String(length=120), nullable=False),
    sa.Column('classification_confidence', sa.Float(), nullable=False),
    sa.Column('classification_reason', sa.Text(), nullable=False),
    sa.Column('classifier_name', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['import_job_id'], ['bill_import_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['raw_transaction_id'], ['raw_transactions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_normalized_transactions_dedupe_key'), 'normalized_transactions', ['dedupe_key'], unique=False)
    op.create_table('merged_transaction_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('merged_transaction_id', sa.Integer(), nullable=False),
    sa.Column('normalized_transaction_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['merged_transaction_id'], ['merged_transactions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['normalized_transaction_id'], ['normalized_transactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('merged_transaction_members')
    op.drop_index(op.f('ix_normalized_transactions_dedupe_key'), table_name='normalized_transactions')
    op.drop_table('normalized_transactions')
    op.drop_table('task_subitems')
    op.drop_table('task_status_history')
    op.drop_table('raw_transactions')
    op.drop_table('user_preferences')
    op.drop_table('tasks')
    op.drop_table('model_call_logs')
    op.drop_table('merged_transactions')
    op.drop_table('bill_import_jobs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
